name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, gd, exif, iconv, fileinfo
      - run: composer install
      - run: composer analyze
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        package:
          - php: 8.3
            laravel: ^10.0
          - php: 8.3
            laravel: ^11.0
          - php: 8.3
            laravel: ^12.0
        stability: [prefer-lowest, prefer-stable]
    name: P${{ matrix.package.php }} - L${{ matrix.package.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.package.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - run: |
          composer require "illuminate/support:${{ matrix.package.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - run: composer test
